### ISSUE TITLE
[Feature] Add flags to Stack command

### ISSUE THREAD

**Issue by Ultr4Anubis** [SIsilicon/WorldEdit-BE-Docs#7]
Currently you cannot add any flags to the stack command, if so currently undocumented.

It would be nice for a `-a` flag that ignore air blocks

**Comment by SIsilicon** [comment]
Might be best to add this to the other repo that holds the addon. Documentation for the commands are auto-generated, so -a likely doesn't exist right now.

Closing as this issue better fits the addon's repo.
